Luxury collection
hlxsites/hsf-commonmoves pull request #100
Opened 2023-05-17 21:01 UTC by irenelagno

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix(https://github.com/hlxsites/hsf-commonmoves/issues/78)

Test URLs:

Before: https://main--hsf-commonmoves--hlxsites.hlx.page/luxury-collection
-After: https://luxury-collection--hsf-commonmoves--hlxsites.hlx.page/luxury-collection

2023-05-17 22:09 UTC, bstopp requested changes
There seems to be a lot of unique/one-off CSS that assumes specific structure and/or organization. My guess is, this came from the live site directly.

Let's reduce the changes to the existing blocks down to theme (background/font color) and font options, and see how much of a delta that is off the current site.

The fewer variations, the better i think.

2023-05-17 22:09 UTC, bstopp commented on blocks/columns/luxury-collection-template.css
> +.luxury-collection .columns.block p{
I don't know if we want to have the Lux experience be unique to it, or if we can just use the existing defintions, and just change the color and maybe the fonts.

Having a fully unique experience for lux seems over the top and too much effort to maintain in the long run?

2023-05-17 22:09 UTC, bstopp commented on blocks/columns/luxury-collection-template.css
> +    float: left;
Will this assumption hold true for all lux columns with an image? Will it always float on the left?

2023-05-18 15:06 UTC, irenelagno commented on blocks/columns/luxury-collection-template.css
> +    font: normal normal 300 50px/56px var(--font-family-gotham);
fixeded

2023-05-18 15:23 UTC, irenelagno commented on blocks/columns/luxury-collection-template.css
> +    letter-spacing: 2.08px;
fixed

2023-05-19 16:20 UTC, bstopp approved these changes
One minor thing but otherwise looks good!

2023-05-19 16:20 UTC, bstopp commented on styles/styles.css
> +  --heading-font-size-xxxxl: 50px;
Shrink this down to xxxl; 2px shouldn't be that big of a deal for the change in experience.

2023-05-19 20:40 UTC, bstopp approved these changes

2023-05-19 21:08 UTC, merged