Add Testimonials carousel
hlxsites/hsf-commonmoves pull request #231
Opened 2024-05-20 05:28 UTC by RitwikSrivastava

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #159

Test URLs:
- Before: https://main--hsf-commonmoves--hlxsites.hlx.page/
- After: https://ritsriva-carousel--hsf-commonmoves--hlxsites.hlx.page/drafts/ritsriva/nancy

2024-05-20 17:24 UTC, bstopp requested changes
Please change this block to be 'agent-testimonials' or something as carousel is too generic.

Update the fetch to use a page metadata property that is the agent ID as discussed.

For the draft page, only have this block on the page to check it's PSI score in a stand-alone context.

2024-05-22 06:36 UTC, RitwikSrivastava commented
> Please change this block to be 'agent-testimonials' or something as carousel is too generic.
> 
> Update the fetch to use a page metadata property that is the agent ID as discussed.
> 
> For the draft page, only have this block on the page to check it's PSI score in a stand-alone context.

Updated to incorporate the above review points.

2024-05-23 12:56 UTC, bstopp requested changes

2024-05-28 12:52 UTC, bstopp approved these changes

2024-05-28 16:05 UTC, merged