Quote Block, Hero Block bug fix
hlxsites/hsf-commonmoves pull request #263
Opened 2024-07-27 16:35 UTC by jindaliiita

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix 

Test URLs:
- Before: https://main--hsf-commonmoves--hlxsites.hlx.page/drafts/piyush/cid-temp-doc-19-4
- After: https://quote-changes--hsf-commonmoves--hlxsites.hlx.page/drafts/piyush/cid-temp-doc-19-4

2024-07-29 16:19 UTC, bstopp reviewed
Shouldn't this only be applied if there is an agent profile to display?

2024-07-31 05:14 UTC, jindaliiita commented
@bstopp Can you review this PR again

2024-08-08 16:09 UTC, bstopp requested changes

2024-08-08 16:09 UTC, bstopp commented on styles/styles.css
> +@media screen and (min-width: 992px) {
We don't have this breakpoint. it's only 600, 900, 1200.

2024-08-08 16:09 UTC, bstopp commented on blocks/hero/search/search.css
> +@media screen and (min-width: 1200px) and (max-width: 1400px) {
Why do we stop at 1400px?

2024-08-13 12:24 UTC, bstopp approved these changes

2024-08-13 14:19 UTC, merged