fixed quotation marks, added title
hlxsites/hsf-commonmoves pull request #57
Opened 2023-04-24 21:57 UTC by badvision

Fix #48 

Test URLs:
- Before: https://main--hsf-commonmoves--hlxsites.hlx.page/
- After: https://quote-title--hsf-commonmoves--hlxsites.hlx.page/

2023-04-25 17:25 UTC, bstopp requested changes

2023-04-25 17:25 UTC, bstopp commented on blocks/quote-carousel/quote-carousel.js
> +  const title = block.querySelector('div > div > div > div > div').textContent;
This should be based on row, not column.

First row is title, second row is the link to the sheet with the quotes.

2023-04-26 19:54 UTC, bstopp requested changes
The title doesn't rotate with the carousel itself. It's also not included inside the box when in mobile view.

2023-04-26 19:54 UTC, bstopp commented on blocks/quote-carousel/quote-carousel.js
> +let alreadyDeferred = false;
I assume this is to check if the delayed JS is already loaded?

2023-04-26 20:01 UTC, bstopp commented
Also, things are off center on some viewports
<img width="284" alt="Seller_Testimonials" src="https://user-images.githubusercontent.com/6520270/234689262-dd7adedf-3412-42a9-a718-fb975dd60ce2.png">

2023-04-27 15:00 UTC, badvision commented
> The title doesn't rotate with the carousel itself. It's also not included inside the box when in mobile view.

Crud!  Ok that is good to know.  I'll work on that.

2023-04-28 18:46 UTC, bstopp approved these changes

2023-04-28 21:16 UTC, bstopp approved these changes

2023-04-28 21:19 UTC, merged